### ISSUE TITLE
Concept Clarity Correction.

### ISSUE THREAD

**Issue by katyhuff** [arfc/2020-fairhurst-hydrogen-production#4]
I think this sentence fundamentally misrepresents the issue:
"Although using hydrogen does not produce CO2, some of the hydrogen production methods still do it."

The hydrogen production methods that produce CO2 (e.g. methane reforming) capture that CO2 on site. This is not the source of CO2 that is of concern. 

ALL hydrogen production methods are only as carbon-free as the source of energy they rely on (electric, heat, or both) to drive the process. *That* is where the main CO2 issue exists in a hydrogen economy, and that is where nuclear comes in. 

 This issue can be closed with a pull request to the paper that clarifies this.

**Comment by robfairh** [comment]
Closed with #8
