### ISSUE TITLE
Zotero entries missing metadata

### ISSUE THREAD

**Issue by katyhuff** [arfc/2020-fairhurst-hydrogen-production#9]
As noted in #3 the zotero entries for this are missing lots of key metadata.
![image](https://user-images.githubusercontent.com/393899/73138013-9bca9780-4023-11ea-8450-4f4396b3f1fa.png)

Please review zotero standards and process [here](http://arfc.github.io/manual/guides/zotero).
This issue can be closed when zotero, the bib file, and the refs in the document have been updated  to include authors, years, and titles for all references.

**Comment by robfairh** [comment]
I have a question about that. There are a few websites with no authors. For example, 'Hydrogen Production' is a website but it does not have an author specified on the web page. So in the .bib in the repository, I added the author: 'Office of Energy Efficiency and Renewable Energy'. And then in the references of the abstract appears like this:
![image](https://user-images.githubusercontent.com/43791150/73144849-52a03500-406f-11ea-849d-394b8c3e54b8.png)
Should I complete the rest of the metadata in the same way?

**Comment by katyhuff** [comment]
1) It's best to use archival primary sources (reports, journal articles) unless it absolutely can't be avoided. 
2) If it can't be avoided, my recommendation in the first case, for example, cases is to name the author as "DOE". The institution can be "DOE Office of Energy Efficiency and Renewable Energy". In zotero, you can make the authorname a single word (no first name.). 


All references must have an Author, Title, and Date.
